<a href="https://colab.research.google.com/github/anushabershilla/Data-science-ML/blob/main/Loanprojectallmodel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('Loandataset.csv')
display(df.head())
df.info
df.isnull().sum()

Saving Loandataset.csv to Loandataset.csv

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [ ]:
# Data cleaning
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)
df['Self_Employed'].fillna(df['Self_Employed'].mode()[0], inplace=True)
df['Married'].fillna(df['Married'].mode()[0], inplace=True)
df['Education'].fillna(df['Education'].mode()[0], inplace=True)
#Numeric mean

df['LoanAmount'].fillna(df['LoanAmount'].mean(), inplace=True)
df['ApplicantIncome'].fillna(df['ApplicantIncome'].mean(),inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0],inplace=True)
df['CoapplicantIncome'].fillna(0, inplace=True)
#important feature

df['Credit_History'].fillna(df['Credit_History'].mode()[0],inplace=True)
df['Property_Area'].fillna(df['Property_Area'].mode()[0], inplace=True)
df.isnull().sum()

/tmp/ipykernel_771/2749091678.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
/tmp/ipykernel_771/2749091678.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)
/tmp/ipykernel_771/2749091678.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Self_Employed'].fillna(df['Self_Employed'].mode()[0], inplace=True)
/tmp/ipykernel_771/2749091678.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Married'].fillna(df['Married'].mode()[0], inplace=True)
/tmp/ipykernel_771/2749091678.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Education'].fillna(df['Education'].mode()[0], inplace=True)
/tmp/ipykernel_771/2749091678.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['LoanAmount'].fillna(df['LoanAmount'].mean(), inplace=True)
/tmp/ipykernel_771/2749091678.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['ApplicantIncome'].fillna(df['ApplicantIncome'].mean(),inplace=True)
/tmp/ipykernel_771/2749091678.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0],inplace=True)
/tmp/ipykernel_771/2749091678.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['CoapplicantIncome'].fillna(0, inplace=True)
/tmp/ipykernel_771/2749091678.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Credit_History'].fillna(df['Credit_History'].mode()[0],inplace=True)
/tmp/ipykernel_771/2749091678.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Property_Area'].fillna(df['Property_Area'].mode()[0], inplace=True)

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [ ]:
df['Loan_Status']=(df['Credit_History']==1)&(df['ApplicantIncome']>3000).astype(int)
df['Loan_Status'].value_counts()

Loan_Status
True     231
False    136
Name: count, dtype: int64

In [ ]:
#Encoding
df['Gender'] = df['Gender'].map({'Male':0,'Female':1})
df['Married'] = df['Married'].map({'Yes':1,'No':0})
df['Education'] = df['Education'].map({'Graduate':1,'Not Graduate':0})
df['Self_Employed'] = df['Self_Employed'].map({'Yes':1,'No':0})

#onehot Encoding
df['Dependents']=df['Dependents'].replace('3+','3').astype('int')

# Check if 'Property_Area' column exists before one-hot encoding
if 'Property_Area' in df.columns:
    df=pd.get_dummies(df,columns=['Property_Area'])
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Loan_ID                  367 non-null    object
 1   Gender                   367 non-null    int64
 2   Married                  367 non-null    int64
 3   Dependents               367 non-null    int64
 4   Education                367 non-null    int64
 5   Self_Employed            367 non-null    int64
 6   ApplicantIncome          367 non-null    int64
 7   CoapplicantIncome        367 non-null    int64
 8   LoanAmount               367 non-null    float64
 9   Loan_Amount_Term         367 non-null    float64
 10  Credit_History           367 non-null    float64
 11  Loan_Status              367 non-null    bool
 12  Property_Area_Rural      367 non-null    bool
 13  Property_Area_Semiurban  367 non-null    bool
 14  Property_Area_Urban      367 non-null    bool
dtypes: bool(4), float64(3), int64(7), object(1)
memory usage: 33.1+ KB

In [ ]:
#Total income
df['Total_Income']=df['ApplicantIncome']+df['CoapplicantIncome']

#Loan to income Ratio
df['Loan_to_Income']=df['LoanAmount'] /df['Total_Income']
#EMI  Loan pressure
df['EMI']= df['LoanAmount']/(df['Loan_Amount_Term'])
# income per person
df['Income_per_Person']=df['Total_Income'] /(df['Dependents']+1)

df.drop('Loan_ID',axis=1,inplace=True)
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Gender                   367 non-null    int64
 1   Married                  367 non-null    int64
 2   Dependents               367 non-null    int64
 3   Education                367 non-null    int64
 4   Self_Employed            367 non-null    int64
 5   ApplicantIncome          367 non-null    int64
 6   CoapplicantIncome        367 non-null    int64
 7   LoanAmount               367 non-null    float64
 8   Loan_Amount_Term         367 non-null    float64
 9   Credit_History           367 non-null    float64
 10  Loan_Status              367 non-null    bool
 11  Property_Area_Rural      367 non-null    bool
 12  Property_Area_Semiurban  367 non-null    bool
 13  Property_Area_Urban      367 non-null    bool
 14  Total_Income             367 non-null    int64
 15  Loan_to_Income           367 non-null    float64
 16  EMI                      367 non-null    float64
 17  Income_per_Person        367 non-null    float64
dtypes: bool(4), float64(6), int64(8)
memory usage: 41.7 KB

In [ ]:
#Data set
X=df.drop('Loan_Status',axis=1)
y=df['Loan_Status']

# Train Test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

#Random forest

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)
print("RF Accuracy:", accuracy_score(y_test, rf_pred))

#Gradient Booster

from sklearn.ensemble import GradientBoostingClassifier

gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)

gb_pred = gb.predict(X_test)
print("GB Accuracy:", accuracy_score(y_test, gb_pred))

#XGBooster
from xgboost import XGBClassifier

xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train, y_train)

xgb_pred = xgb.predict(X_test)
print("XGB Accuracy:", accuracy_score(y_test, xgb_pred))

#Cross validation
from sklearn.model_selection import cross_val_score

print("RF CV:", cross_val_score(rf, X, y, cv=3).mean())
print("GB CV:", cross_val_score(gb, X, y, cv=3).mean())
print("XGB CV:", cross_val_score(xgb, X, y, cv=3).mean())

RF Accuracy: 1.0
GB Accuracy: 1.0

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:58:36] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

XGB Accuracy: 1.0
RF CV: 0.9972677595628415
GB CV: 0.9972677595628415
XGB CV: 0.9945355191256832

/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:58:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:58:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
/usr/local/lib/python3.12/dist-packages/xgboost/training.py:200: UserWarning: [09:58:37] WARNING: /__w/xgboost/xgboost/src/learner.cc:782:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

In [ ]:
import pandas as pd

model = gb  # or best model

importance = model.feature_importances_

imp_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importance
}).sort_values(by='Importance', ascending=False)

print(imp_df)

                    Feature    Importance
5           ApplicantIncome  7.109232e-01
9            Credit_History  2.890768e-01
14           Loan_to_Income  3.021818e-16
16        Income_per_Person  2.206357e-16
6         CoapplicantIncome  1.159609e-16
0                    Gender  0.000000e+00
4             Self_Employed  0.000000e+00
1                   Married  0.000000e+00
2                Dependents  0.000000e+00
13             Total_Income  0.000000e+00
8          Loan_Amount_Term  0.000000e+00
3                 Education  0.000000e+00
10      Property_Area_Rural  0.000000e+00
11  Property_Area_Semiurban  0.000000e+00
15                      EMI -3.576587e-18
12      Property_Area_Urban -5.126441e-18
7                LoanAmount -3.751442e-17

In [ ]:
new_customer = pd.DataFrame([
    {
        'Gender': 0, # Assuming Male
        'Married': 1, # Assuming Yes
        'Dependents': 0, # Assuming 0 dependents
        'Education': 1, # Assuming Graduate
        'Self_Employed': 0, # Assuming No
        'ApplicantIncome': 50000,
        'CoapplicantIncome': 0, # Assuming no coapplicant
        'LoanAmount': 20000,
        'Loan_Amount_Term': 360.0, # Assuming a common loan term
        'Credit_History': 1.0,
        'Property_Area_Rural': 0, # Assuming not Rural
        'Property_Area_Semiurban': 1, # Assuming Semiurban
        'Property_Area_Urban': 0, # Assuming not Urban
        'Total_Income': 50000 + 0, # ApplicantIncome + CoapplicantIncome
        'Loan_to_Income': 20000 / (50000 + 0),
        'EMI': 20000 / 360.0,
        'Income_per_Person': (50000 + 0) / (0 + 1) # Total_Income / (Dependents + 1)
    }
])

# Ensure the columns match the training data 'X'
new_customer = new_customer[X.columns]

print("Prediction:", model.predict(new_customer))

Prediction: [ True]

In [ ]:

import pickle

pickle.dump(model, open('loan_model.pkl', 'wb'))